### ISSUE TITLE
empty images without stars raising exception (EBV2)

### ISSUE THREAD

**Issue by mpgh** [pyDANDIA/pyDANDIA#140]
/pyDANDIA/stage4.py", line 873, in resample_image_stamps
    raise ValueError("Not enough matching stars! Switching to translation")
ValueError: Not enough matching stars! Switching to translation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pyDANDIA/pyDANDIA/run_stage.py", line 261, in <module>
    run_stage_stand_alone()
  File "pyDANDIA/pyDANDIA/run_stage.py", line 85, in run_stage_stand_alone
    (status, report) = stage4.run_stage4(setup)
  File "pyDANDIA/stage4.py", line 226, in run_stage4
    image_red_status = resample_image_stamps(new_images, reference_image_name, reference_image_directory, reduction_metadata, setup,
  File "pyDANDIA/stage4.py", line 883, in resample_image_stamps
    model_final = init_transform
NameError: name 'init_transform' is not defined

**Comment by ebachelet** [comment]
OK I just pushed a correction (did not have time to try it unfortunately, I am setting up a new machine)

**Comment by mpgh** [comment]
Unfortunately, the problem still seems to persist and I even encountered it with an image containing stars. I will double-check.

**Comment by mpgh** [comment]
I am trying to provide  more details, checked that I have updated everything to the latest version and the message I am getting is: 
Traceback (most recent call last):
  File "stage4.py", line 873, in resample_image_stamps
    raise ValueError("Not enough matching stars! Switching to translation")
ValueError: Not enough matching stars! Switching to translation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pyDANDIA/pyDANDIA/run_stage.py", line 261, in <module>
    run_stage_stand_alone()
  File "pyDANDIA/pyDANDIA/run_stage.py", line 85, in run_stage_stand_alone
    (status, report) = stage4.run_stage4(setup)
  File "pyDANDIA/stage4.py", line 226, in run_stage4
    image_red_status = resample_image_stamps(new_images, reference_image_name, reference_image_directory, reduction_metadata, setup,
  File "pyDANDIA/stage4.py", line 883, in resample_image_stamps
    model_final = init_transform
NameError: name 'init_transform' is not defined

**Comment by ebachelet** [comment]
In the corrected branch (EBV2), line 883 is:
                    init_transform = rotate_shifts_transform(guess,reference_image.shape)

so this is different to what you shown. Are you sure you correctly update?

**Comment by mpgh** [comment]
cloning the repo again works and reinstalling works, you are right.
